import { cookies } from "next/headers";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { ThemeProvider } from "next-themes";

import { Header } from "../shared/ui/header/header";
import { SidebarComponent } from "../shared/ui/sidebar";

import { NAV_ITEMS } from "../shared/config/constants/navitem.config";

import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const theme = cookie.get("theme")?.value || "system";
  return (
    <html
      lang="en"
      data-theme={theme}
      className={theme}
      suppressHydrationWarning
    >
      <body className={`${roboto.variable} antialiased`}>
        <div className="flex min-h-screen bg-gray-50">
          <SidebarComponent.Root>
            <SidebarComponent.Sidebar>
              {NAV_ITEMS.map((item) => (
                <SidebarComponent.SidebarItem key={item.route} {...item} />
              ))}
            </SidebarComponent.Sidebar>
          </SidebarComponent.Root>
          <div className="flex-1 flex flex-col">
            <Header />
            <main className="flex-1 overflow-auto py-8 px-4">
              <div className="max-w-7xl mx-auto">
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                  enableColorScheme
                >
                  {children}
                </ThemeProvider>
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
